orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
version: 2.1
jobs:
  build:
    working_directory: ~/example
    docker:
      - image: circleci/node:14.17.5-browsers
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
              - node_modules
      # Test the source code
      - run:
          name: Testing
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
      # Lint the source code
      #- run:
      #    name: Linting
      #    command: npm run lint
workflows:
  version: 2
  my_workflow:
    jobs:
      - build